lldp-util: Silence format-security warning
Since the inclusion of SECURITY_STRINGFORMAT on
30f9a507 , which includes -Werror=format-security
errors are caused during build such as:

lldp_util.c: In function 'lldp_open':
lldp_util.c:150:5: error: format not a string literal _
    and no format arguments [-Werror=format-security]
snprintf(ifr.ifr_name, IFNAMSIZ, interface);

While the correct way is to fix this within the source code,
for now, as a temporary fix, we can stop the warning from
throwing an error by appending -Wno-format-security to CFLAGS.

Signed-off-by: Alejandro Enedino Hernandez Samaniego <aehs29@gmail.com>