CFLAGS: Silence security and gcc8 warnings (temporarily) for several packages
Since the adoption of GCC 8 > in Yocto along with the
introduction of SECURITY_STRINGFORMAT on 30f9a507,
several errors appeared through several software
packages included in the DISTRO (these either used
to be warnings before the SECURITY_CFLAGS were
introduced or they were not even warnings before
GCC 8.

The GCC 8 enabled warnings are documented here:
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

Some of these errors show up like this:

-----------------
lldp_util.c: In function 'lldp_open':
lldp_util.c:150:5: error: format not a string literal _
    and no format arguments [-Werror=format-security]
snprintf(ifr.ifr_name, IFNAMSIZ, interface);
-----------------

-----------------
| log.c: In function 'obmc_log_by_prio':
| log.c:184:20: error: format not a string literal and no format
arguments [-Werror=format-security]
|     fprintf(stream, buf);
-----------------

While the correct way to fix this is to do it within the
source code of each package (they shouldn't be showing
warnings anyway), as a TEMPORARY fix these warnings have
been silenced for now, some of these include:

 -Wno-format-security
 -Wno-unused-result
 -Wno-format-truncation
 -Wno-format-overflow
 -Wno-implicit-function-declaration

On each package these were all silenced on a per-need
basis, meaning that all the other security flags should
still be enabled.

In only 3 packages the whole SECURITY_CFLAGS had to be
disabled:
- obmc-pal
- libpal
- me-util

While some of these may only actually be warnings, a few
could potentially mean security threats, hence one of
the reasons I decide to squash all silencing commits into
a single one is to make them either all work or not, to
force them to be analyzed on an case by case basis.

Signed-off-by: Alejandro Enedino Hernandez Samaniego <aehs29@gmail.com>