mterm: Silence warning stringop-truncation
GCC8 enables -Wstringop-truncation, documented on:
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

When using -Wall, this causes errors while building mterm
like the following:

mTerm_helper.c:34:5: error: strncpy specified bound 16 _
    equals destination size [-Werror=stringop-truncation]
strncpy(g_fru, dev, sizeof(g_fru));

While the correct way is to fix this within the source code,
for now, as a temporary fix, we can stop the warning from
throwing an error.

Signed-off-by: Alejandro Enedino Hernandez Samaniego <aehs29@gmail.com>