liblog: Silence format-security warning
Since the inclusion of SECURITY_STRINGFORMAT on
30f9a507 , which includes -Werror=format-security
errors are caused during build such as:

| log.c: In function 'obmc_log_by_prio':
| log.c:184:20: error: format not a string literal and no format
arguments [-Werror=format-security]
|     fprintf(stream, buf);

While the correct way is to fix this within the source code,
for now, as a temporary fix, we can stop the warning from
throwing an error by appending -Wno-format-security to CFLAGS.

Signed-off-by: Alejandro Enedino Hernandez Samaniego <aehs29@gmail.com>